### ISSUE TITLE
Plugin fails to run. 

### ISSUE THREAD

**Issue by xavieER286** [Feuleur/blender-mhworld-tools-suite#2]
When I attempt to install version 1.3.5 the blender console is reporting the following error. 

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender-mhworld-tools-suite-1'

Attempts to import any files using version 1.3.3 fail as well with error 

Python: Traceback (most recent call last):
  File "C:\Users\SOL\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-mhworld-tools-suite\mod3\ui.py", line 97, in execute
KeyError: 'bpy_prop_collection[key]: key "mhworld_tool_suite" not found'

Not certain if I missed a step or not.

**Comment by Brondy90** [comment]
I have Blender version 4.1, but I encountered the same error. I solved it by extracting the archive, renaming the folder to "blender-mhworld-tools-suite-1," and then compressing it back into a zip file. It was just a naming issue.

**Comment by cloudberryowo** [comment]
i cant import anything i get traceback errors
